const button = document.querySelector("#button");

let adjPersonality = [
  "admirable",
  "adaptable",
  "adventurous",
  "agreeable",
  "agile",
  "amazing",
  "ambidextrous",
  "angelic",
  "astute",
  "astonishing",
  "awe-inspiring",
  "beloved",
  "benevolent",
  "blameless",
  "blissful",
  "brainy",
  "brave",
  "brilliant",
  "bubbly",
  "buoyant",
  "calm",
  "caring",
  "chipper",
  "clever",
  "companionable",
  "compassionate",
  "confident",
  "congenial",
  "courageous",
  "creative",
  "curious",
  "daring",
  "dauntless",
  "dedicated",
  "deft",
  "delightful",
  "diligent",
  "diplomatic",
  "dynamic",
  "earnest",
  "effervescent",
  "empathetic",
  "empowered",
  "energetic",
  "engaging",
  "enthusiastic",
  "ethical",
  "euphoric",
  "extraordinary",
  "fantastic",
  "fascinating",
  "fearless",
  "fiery",
  "friendly",
  "frisky",
  "gallant",
  "generous",
  "genius",
  "gentle",
  "genuine",
  "gifted",
  "giving",
  "goodhearted",
  "gregarious",
  "hard-working",
  "hilarious",
  "holy",
  "honest",
  "hopeful",
  "hospitable",
  "humane",
  "humble",
  "idealistic",
  "imaginative",
  "impassioned",
  "independent",
  "industrious",
  "ingenious",
  "innocent",
  "inquisitive",
  "insightful",
  "inspiring",
  "intelligent",
  "intriguing",
  "inventive",
  "invincible",
  "jovial",
  "joyful",
  "jubilant",
  "kind",
  "laudable",
  "legendary",
  "likeable",
  "logical",
  "loyal",
  "lucky",
  "magnanimous",
  "mature",
  "meditative",
  "mellow",
  "melodious",
  "memorable",
  "meticulous",
  "miraculous",
  "motivated",
  "motivational",
  "multidimensional",
  "musical",
  "mythical",
  "mystical",
  "neighborly",
  "nimble",
  "noble",
  "open-hearted",
  "open-minded",
  "optimistic",
  "original",
  "passionate",
  "patient",
  "peaceable",
  "peerless",
  "perceptive",
  "persistent",
  "personable",
  "perspicacious",
  "philosophical",
  "playful",
  "poetic",
  "pragmatic",
  "praiseworthy",
  "proactive",
  "profound",
  "pure",
  "quick-witted",
  "quirky",
  "rational",
  "reasonable",
  "refreshing",
  "reliable",
  "remarkable",
  "resilient",
  "resourceful",
  "revolutionary",
  "sassy",
  "savvy",
  "self-assured",
  "self-confident",
  "selfless",
  "sensible",
  "sensitive",
  "serene",
  "sincere",
  "sociable",
  "sophisticated",
  "special",
  "spirited",
  "steadfast",
  "strong-willed",
  "supportive",
  "sweet",
  "sympathetic",
  "tactful",
  "talented",
  "tenacious",
  "thoughtful",
  "thriving",
  "tolerant",
  "trailblazing",
  "tranquil",
  "trustworthy",
  "trusty",
  "tuneful",
  "unflappable",
  "upbeat",
  "valiant",
  "versatile",
  "vigilant",
  "virtuous",
  "visionary",
  "vivacious",
  "warm-hearted",
  "whimsical",
  "wholehearted",
  "wise",
  "witty",
  "wonderful",
  "wondrous",
  "worthy",
  "zesty"
];

let adjAppearance = [
  "adorable",
  "alluring",
  "angelic",
  "beaming",
  "beautiful",
  "breathtaking",
  "celestial",
  "charming",
  "chic",
  "classy",
  "colorful",
  "cute",
  "dainty",
  "dapper",
  "darling",
  "dashing",
  "dazzling",
  "debonair",
  "delicate",
  "delightful",
  "distinctive",
  "divine",
  "dreamy",
  "elegant",
  "electrifying",
  "enchanting",
  "entrancing",
  "enticing",
  "ethereal",
  "exquisite",
  "eye-catching",
  "fabulous",
  "fair",
  "fancy",
  "fashionable",
  "faultless",
  "fetching",
  "flamboyant",
  "flawless",
  "foxy",
  "fragrant",
  "flashy",
  "gilded",
  "glamorous",
  "gleaming",
  "glimmering",
  "glittering",
  "glorious",
  "glowing",
  "golden",
  "gorgeous",
  "grand",
  "graceful",
  "heavenly",
  "hypnotic",
  "immaculate",
  "impeccable",
  "incredible",
  "incandescent",
  "intoxicating",
  "inviting",
  "irresistible",
  "jaunty",
  "lavish",
  "lovely",
  "luminous",
  "lustrous",
  "luxuriant",
  "luxurious",
  "majestic",
  "magnetic",
  "marvelous",
  "mesmerizing",
  "opalescent",
  "opulent",
  "peachy",
  "perfect",
  "picturesque",
  "plush",
  "poised",
  "polished",
  "posh",
  "precious",
  "pretty",
  "pristine",
  "queenly",
  "radiant",
  "rapturous",
  "refined",
  "regal",
  "rosy-cheeked",
  "scintillating",
  "shimmering",
  "shining",
  "shiny",
  "silken",
  "silky",
  "sleek",
  "snazzy",
  "spectacular",
  "spangly",
  "sparkling",
  "sparkly",
  "splendid",
  "spotless",
  "spry",
  "spunky",
  "statuesque",
  "stellar",
  "sterling",
  "stunning",
  "stylish",
  "sun-kissed",
  "sylvan",
  "symmetrical",
  "tasteful",
  "timeless",
  "transcendent",
  "translucent",
  "twinkling",
  "velvety",
  "vibrant",
  "vivacious",
  "winsome",
  "winged",
  "youthful"
];

let nouns = [
  "angel fish",
  "anemone",
  "arctic fox",
  "artiste",
  "axolotl",
  "baby dragon",
  "bald eagle",
  "blossom",
  "bluebell",
  "buttercup",
  "butterfly",
  "calla lily",
  "capybara",
  "centaur",
  "chameleon",
  "child",
  "chinchilla",
  "chrysanthemum",
  "comet",
  "court jester",
  "daisy",
  "daffodil",
  "deer",
  "dewdrop",
  "dove",
  "dragonfly",
  "dynamo",
  "eagle",
  "egret",
  "elf",
  "emperor penguin",
  "emu",
  "enchantress",
  "entrepreneur",
  "fairy",
  "fairytale creature",
  "fawn",
  "fennec fox",
  "flamingo",
  "flying fox",
  "forest creature",
  "forget-me-not",
  "galaxy",
  "genie",
  "gerber daisy",
  "goddess",
  "hawk",
  "heron",
  "heroine",
  "hippogriff",
  "house cat",
  "hummingbird",
  "humanitarian",
  "hydrangea",
  "hyacinth",
  "infant",
  "iris",
  "jellyfish",
  "kangaroo",
  "king cobra",
  "koala",
  "ladybug",
  "leopard",
  "leprechaun",
  "librarian",
  "lilac",
  "lion fish",
  "lioness",
  "lynx",
  "mage",
  "magician",
  "magpie",
  "maiden",
  "manta ray",
  "marigold",
  "meadow",
  "meerkat",
  "mermaid",
  "mink",
  "miracle worker",
  "moon goddess",
  "moonflower",
  "morning glory",
  "mountain lion",
  "moth",
  "musk-ox",
  "narwhal",
  "nebula",
  "newborn",
  "newborn baby",
  "nightengale",
  "noblewoman",
  "Olympian",
  "optimist",
  "orchid",
  "ostrich",
  "owl",
  "panther",
  "panda",
  "pegasus",
  "penguin",
  "petunia",
  "phoenix",
  "philosopher",
  "pixie",
  "pioneer",
  "poet",
  "poet laureate",
  "polar bear",
  "primrose",
  "problem solver",
  "protagonist",
  "queen",
  "rainbow",
  "raindrop",
  "red panda",
  "reindeer",
  "river leaf",
  "river otter",
  "rose",
  "sage",
  "saint",
  "sandhill crane",
  "scion",
  "sea lion",
  "sea otter",
  "sea serpent",
  "shooting star",
  "sky fox",
  "slow loris",
  "snow leopard",
  "snowdrop",
  "sorceress",
  "spider monkey",
  "sparrow",
  "sportswoman",
  "starfish",
  "sun goddess",
  "sunfish",
  "super hero",
  "superwoman",
  "sunspot",
  "swan",
  "tigris",
  "tiger lily",
  "treasure",
  "tree shark",
  "trailblazer",
  "unicorn",
  "valedictorian",
  "violet",
  "water lily",
  "water moccasin",
  "water sprite",
  "wildflower",
  "wind chime",
  "witch",
  "wizard",
  "wordsmith",
  "workhorse",
  "wunderkind"
];

function generateCompliment() {
  let randomIndexPersonality = Math.floor(
    Math.random() * adjPersonality.length
  );
  let personality = adjPersonality[randomIndexPersonality];

  let randomIndexAppearance = Math.floor(Math.random() * adjAppearance.length);
  let appearance = adjAppearance[randomIndexAppearance];

  let randomIndexNoun = Math.floor(Math.random() * nouns.length);
  let noun = nouns[randomIndexNoun];

  let compliment =
    "Emily, you " + personality + ", " + appearance + " " + noun + "...";

  document.querySelector(".compliment-text").textContent = compliment;
  console.log(compliment);
}

// Event Listener
button.addEventListener("click", generateCompliment);
